// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'restaurant.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Restaurant _$RestaurantFromJson(Map<String, dynamic> json) => Restaurant(
      id: json['id'] as int?,
      name: json['name'] as String?,
      description: json['description'] as String?,
      locationId: json['location_id'],
      image: json['image'] as String?,
      rating: json['rating'] as String?,
      promotext: json['promotext'],
      deliveryTime: json['delivery_time'] as String?,
      priceRange: json['price_range'] as String?,
      isPureveg: json['is_pureveg'] as int?,
      slug: json['slug'] as String?,
      placeholderImage: json['placeholder_image'],
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      certificate: json['certificate'],
      restaurantCharges: json['restaurant_charges'],
      deliveryCharges: json['delivery_charges'],
      address: json['address'] as String?,
      pincode: json['pincode'] as String?,
      landmark: json['landmark'] as String?,
      sku: json['sku'] as String?,
      isActive: json['is_active'] as int?,
      isAccepted: json['is_accepted'] as int?,
      isFeatured: json['is_featured'] as int?,
      commissionRate: json['commission_rate'] as String?,
      governmentTax: json['government_tax'] as String?,
      deliveryType: json['delivery_type'] as int?,
      deliveryRadius: json['delivery_radius'] as int?,
      deliveryChargeType: json['delivery_charge_type'] as String?,
      baseDeliveryCharge: json['base_delivery_charge'] as String?,
      baseDeliveryDistance: json['base_delivery_distance'] as int?,
      extraDeliveryCharge: json['extra_delivery_charge'] as String?,
      extraDeliveryDistance: json['extra_delivery_distance'] as int?,
      minOrderPrice: json['min_order_price'] as String?,
      isNotifiable: json['is_notifiable'] as int?,
      autoAcceptable: json['auto_acceptable'] as int?,
      scheduleData: json['schedule_data'],
      isSchedulable: json['is_schedulable'] as int?,
      orderColumn: json['order_column'] as int?,
      customMessage: json['custom_message'],
    );

Map<String, dynamic> _$RestaurantToJson(Restaurant instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'location_id': instance.locationId,
      'image': instance.image,
      'rating': instance.rating,
      'promotext': instance.promotext,
      'delivery_time': instance.deliveryTime,
      'price_range': instance.priceRange,
      'is_pureveg': instance.isPureveg,
      'slug': instance.slug,
      'placeholder_image': instance.placeholderImage,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'certificate': instance.certificate,
      'restaurant_charges': instance.restaurantCharges,
      'delivery_charges': instance.deliveryCharges,
      'address': instance.address,
      'pincode': instance.pincode,
      'landmark': instance.landmark,
      'sku': instance.sku,
      'is_active': instance.isActive,
      'is_accepted': instance.isAccepted,
      'is_featured': instance.isFeatured,
      'commission_rate': instance.commissionRate,
      'government_tax': instance.governmentTax,
      'delivery_type': instance.deliveryType,
      'delivery_radius': instance.deliveryRadius,
      'delivery_charge_type': instance.deliveryChargeType,
      'base_delivery_charge': instance.baseDeliveryCharge,
      'base_delivery_distance': instance.baseDeliveryDistance,
      'extra_delivery_charge': instance.extraDeliveryCharge,
      'extra_delivery_distance': instance.extraDeliveryDistance,
      'min_order_price': instance.minOrderPrice,
      'is_notifiable': instance.isNotifiable,
      'auto_acceptable': instance.autoAcceptable,
      'schedule_data': instance.scheduleData,
      'is_schedulable': instance.isSchedulable,
      'order_column': instance.orderColumn,
      'custom_message': instance.customMessage,
    };
